<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user/user.proto

namespace User;

if (false) {
    /**
     * This class is deprecated. Use User\GetUserInfoReply\gender instead.
     * @deprecated
     */
    class GetUserInfoReply_gender {}
}
class_exists(GetUserInfoReply\gender::class);
@trigger_error('User\GetUserInfoReply_gender is deprecated and will be removed in the next major release. Use User\GetUserInfoReply\gender instead', E_USER_DEPRECATED);

