<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user/user.proto

namespace GPBMetadata\User;

class User
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a83020a0f757365722f757365722e70726f746f12047573657222240a12" .
            "47657455736572496e666f52657175657374120e0a067573657249641801" .
            "20012809226d0a1047657455736572496e666f5265706c79120f0a077573" .
            "65725f6964180120012809120c0a046e616d65180220012809120b0a0361" .
            "6765180320012805120d0a0570686f6e65180420012809221e0a0667656e" .
            "64657212080a046d616c651000120a0a0666656d616c651001324d0a0855" .
            "736572496e666f12410a0b47657455736572496e666f12182e757365722e" .
            "47657455736572496e666f526571756573741a162e757365722e47657455" .
            "736572496e666f5265706c792200620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

