<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user/user.proto

namespace User\GetUserInfoReply;

use UnexpectedValueException;

/**
 * Protobuf type <code>user.GetUserInfoReply.gender</code>
 */
class gender
{
    /**
     * Generated from protobuf enum <code>male = 0;</code>
     */
    const male = 0;
    /**
     * Generated from protobuf enum <code>female = 1;</code>
     */
    const female = 1;

    private static $valueToName = [
        self::male => 'male',
        self::female => 'female',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(gender::class, \User\GetUserInfoReply_gender::class);

