<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: thread/thread.proto

namespace Thread;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * thread 响应数据
 *
 * Generated from protobuf message <code>thread.TheadReply</code>
 */
final class TheadReply extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string Id = 1;</code>
     */
    private $Id = '';
    /**
     * Generated from protobuf field <code>string Title = 2;</code>
     */
    private $Title = '';
    /**
     * Generated from protobuf field <code>string Image = 3;</code>
     */
    private $Image = '';
    /**
     * Generated from protobuf field <code>string Content = 4;</code>
     */
    private $Content = '';
    /**
     * Generated from protobuf field <code>string CreatedAt = 5;</code>
     */
    private $CreatedAt = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $Id
     *     @type string $Title
     *     @type string $Image
     *     @type string $Content
     *     @type string $CreatedAt
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Thread\Thread::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string Id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->Id;
    }

    /**
     * Generated from protobuf field <code>string Id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->Id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Title = 2;</code>
     * @return string
     */
    public function getTitle()
    {
        return $this->Title;
    }

    /**
     * Generated from protobuf field <code>string Title = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->Title = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Image = 3;</code>
     * @return string
     */
    public function getImage()
    {
        return $this->Image;
    }

    /**
     * Generated from protobuf field <code>string Image = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setImage($var)
    {
        GPBUtil::checkString($var, True);
        $this->Image = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Content = 4;</code>
     * @return string
     */
    public function getContent()
    {
        return $this->Content;
    }

    /**
     * Generated from protobuf field <code>string Content = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setContent($var)
    {
        GPBUtil::checkString($var, True);
        $this->Content = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string CreatedAt = 5;</code>
     * @return string
     */
    public function getCreatedAt()
    {
        return $this->CreatedAt;
    }

    /**
     * Generated from protobuf field <code>string CreatedAt = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setCreatedAt($var)
    {
        GPBUtil::checkString($var, True);
        $this->CreatedAt = $var;

        return $this;
    }

}

